services:
    postgres-projetofinal-persist:
        image: postgres:17.2
        container_name: postgres-projetofinal-persist
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '4002:5432'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
