services:
  postgres-projetofinal-persist:
    image: postgres:16-alpine3.20
    container_name: postgres-projetofinal-persist
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
        - "4002:5432"
    volumes:
        - ./postgres-data:/var/lib/postgresql_16/data
    networks:
       - app-network
         
volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
