version: '3.8'

services:
    app:
        build: .
        container_name: fastapi
        ports:
            - "8000:8000"
        depends_on:
            postgres-persist:
                condition: service_healthy
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres-persist:5432/postgres"
        networks:
            - app-network
        restart: unless-stopped

    postgres-persist:
        image: postgres:17.2
        container_name: postgres-persist
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '4002:5432'
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    app-network:
        driver: bridge
