configs:
  database:
    host: "localhost"
    port: 4002
    username: "postgres"
    password: "postgres"
    name: "postgres"
  server:
        host: "localhost"
        port: 8081
  logging:
      level: "INFO"
      filename: "app/app.log"
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
